### ISSUE TITLE
Problem with drive link

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#40]
Hello, Im getting a problem with drive url. It says this 
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:
```

The link is public and I have tested it by trying to download it using incognito tab but it still doesn't work

**Comment by acheong08** [comment]
The issue is that the link has been accessed too many times. Google disables command line download after ~200 downloads (not by you but in total) of the same file. This is why huggingface is so popular right now. You can send me the link and I'll try to get it onto huggingface

**Comment by RayZ3R0** [comment]
No pretty sure that's not it, The file was literally just uploaded and never used before

**Comment by RayZ3R0** [comment]
Also, I'm getting this error after uploading to huggingface and using the link
```
Loading weights [e3b0c442] from /content/stable-diffusion-webui/models/Stable-diffusion/kuru.ckpt
Error verifying pickled file from /content/stable-diffusion-webui/models/Stable-diffusion/kuru.ckpt:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 98, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, '<'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Traceback (most recent call last):
  File "launch.py", line 251, in <module>
    start()
  File "launch.py", line 246, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 150, in webui
    initialize()
  File "/content/stable-diffusion-webui/webui.py", line 85, in initialize
    modules.sd_models.load_model()
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 248, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 177, in load_model_weights
    if "global_step" in pl_sd:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by acheong08** [comment]
It says you're using the wrong link. It has to be a direct download link ending in .ckpt

**Comment by RayZ3R0** [comment]
It is, here's the one I used https://huggingface.co/Z3R069/kuru-diffusion/blob/main/Tokisaki.ckpt

**Comment by acheong08** [comment]
It's not a direct download link. It should be https://huggingface.co/Z3R069/kuru-diffusion/resolve/main/Tokisaki.ckpt

**Comment by RayZ3R0** [comment]
ohh, thanks

**Comment by RayZ3R0** [comment]
Would be nice if we could use private repos as well, probably with a huggingface token ig?

**Comment by acheong08** [comment]
> Would be nice if we could use private repos as well, probably with a huggingface token ig?

You can change the token used manually in the code. I don't want to include it in the interface as there are idiots who won't understand and mistake it as a requirement. I am already using a default token.

**Comment by acheong08** [comment]
I could make it default and allow edit

**Comment by acheong08** [comment]
Done

**Comment by RayZ3R0** [comment]
ok, thanks
