### ISSUE TITLE
Textual Inversion doesnt work?

### ISSUE THREAD

**Issue by Rorutop** [acheong08/Diffusion-ColabUI#66]
Just learned what Textual Inversion is. I tried to train the AI with downloaded embedding but then it says this?

Arguments: ('blowjob', '0.000005', 1, 1, '/content/sample_data/input', 'textual_inversion', 512, 512, 100000, False, 0, 'once', 100, 100, '/content/stable-diffusion-webui/textual_inversion_templates/hypernetwork.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/textual_inversion/ui.py", line 26, in train_embedding
    assert not shared.cmd_opts.lowvram, 'Training models with lowvram not possible'
AssertionError: Training models with lowvram not possible

its on medvram i checked..

**Comment by acheong08** [comment]
Try without any RAM options (leave that part empty)/ It seems to be a but with https://github.com/AUTOMATIC1111/stable-diffusion-webui where medvram is detected as lowvram

**Comment by Rorutop** [comment]
Nope, still doesnt work

**Comment by acheong08** [comment]
I will need to look into this then

**Comment by Rorutop** [comment]
How is it going now?

**Comment by acheong08** [comment]
Make sure `large_models` is disabled and that you aren't using SD2.0. I have been able to get it working just fine with 1.5 and without vram options

**Comment by Rorutop** [comment]
Well uhh it gives me this:
```
100% 1/1 [00:00<00:00,  5.05it/s]
  0% 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

Applying xformers cross attention optimization.

and says ```Training finished at 0 steps.```

Any way to fix this?

**Comment by Rorutop** [comment]
Wait oops about the closed i

**Comment by Rorutop** [comment]
Well it gives me this:
```100% 1/1 [00:00<00:00,  5.05it/s]
  0% 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Applying xformers cross attention optimization.```

and the train says Training finished at 0 steps.

Anyway to fix this?

**Comment by Rorutop** [comment]
Well it gives me this:
```100% 1/1 [00:00<00:00,  5.05it/s]
  0% 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Applying xformers cross attention optimization.```

and the train says Training finished at 0 steps.

Anyway to fix this?

**Comment by acheong08** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3958#issuecomment-1331284615

I will need to fork StabilityAI's repo and fix it

**Comment by acheong08** [comment]
https://github.com/acheong08/stable-diffusion-webui/commit/4a1bca042edb89de2316cc494b5e61f52847fb37

https://github.com/acheong08/stablediffusion/commit/20eeba8fae43ce5a3ffdaf9b85d08901578eba97

Should be fixed

**Comment by Rorutop** [comment]
Thanks! Anyway another question is there a way to git clone DreamArtist extension to the extensions folder in Colab? Dunno i dont know about coding in colab, i only know lua and haxe

**Comment by Rorutop** [comment]
Nevermind i just figured it myself. Thanks for helping anyway!!
