### ISSUE TITLE
gdrive never works for me

### ISSUE THREAD

**Issue by RayZ3R0** [acheong08/Diffusion-ColabUI#77]
Whenever I run in gdrive, after everything is done downloading, it quits with ^C. I have tried multiple accounts with VPN in multiple locations but it never works when I run in gdrive. VPN and switching account always usually works without gdrive

**Comment by acheong08** [comment]
gdrive might take up more RAM as it is stored in memory before saving all at once. You could share it with me and I'll upload it to huggingface

**Comment by RayZ3R0** [comment]
Nono I want to run in gdrive so the generated images are stored in gdrive cuz I bulk generate a lot of images so sometimes the colab disconnects and all the images are lost and I rage

**Comment by acheong08** [comment]
Ah. Got it. I thought you were downloading from gdrive

**Comment by acheong08** [comment]
Ok. Still seems to be a RAM issue. will check it out rn

**Comment by RayZ3R0** [comment]
Alright

**Comment by acheong08** [comment]
Check if your gdrive storage is full

**Comment by RayZ3R0** [comment]
Nope, it has about 12gb free space

**Comment by acheong08** [comment]
I could possibly tweak it so that images are saved to drive automatically rather than running the whole thing from drive

**Comment by RayZ3R0** [comment]
Yeah that'd be good 😊

**Comment by acheong08** [comment]
btw running in gdrive is working without ^C for me. Might also be a result of Google limits

**Comment by acheong08** [comment]
I do get an error though:
```py
Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/img2img.py", line 152, in img2img
    processed = process_images(p)
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/processing.py", line 549, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/processing.py", line 891, in init
    image = images.flatten(img, opts.img2img_background_color)
  File "/content/drive/MyDrive/AI/stable-diffusion-webui/modules/images.py", line 652, in flatten
    if img.mode == "RGBA":
AttributeError: 'NoneType' object has no attribute 'mode'
```

**Comment by RayZ3R0** [comment]
That's certainly weird, I just started the colab the first time today with run in gdrive selected so I don't get why I'm being limited

**Comment by acheong08** [comment]
Anyways, I'll try to implement the save to gdrive feature by today

**Comment by RayZ3R0** [comment]
Alright, thanks!

**Comment by acheong08** [comment]
I added some code to the dev branch for stable-diffusion-webui. Testing it out

**Comment by acheong08** [comment]
It was annoying trying to add this as @automatic1111 didn't implement a feature to allow specifying this via CLI

**Comment by acheong08** [comment]
Complete and tested. Try it out.

**Comment by RayZ3R0** [comment]
Alright, I think I'll need to do it tomorrow, idk why but every time I start its shutting down with a ^C now, probably on high demand or smth

**Comment by RayZ3R0** [comment]
This is weird asf, I just started the colab the first time today and it shut down with ^C
