### ISSUE TITLE
Merging models doesn't work?

### ISSUE THREAD

**Issue by Rorutop** [acheong08/Diffusion-ColabUI#84]
Another issue again... I just wanted to merge

```Loading /content/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.ckpt...
Loading /content/stable-diffusion-webui/models/Stable-diffusion/AbyssOrangeMix2-hard.safetensors...
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 1795, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/stable-diffusion-webui/modules/extras.py", line 382, in run_modelmerger
    theta_0 = sd_models.read_state_dict(primary_model_info.filename, map_location=devices.get_optimal_device())
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 220, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
Exception: device cuda is invalid```

**Comment by acheong08** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6890

Seems to be a regression from a new commit. Will need to wait for a fix upstream

**Comment by Rorutop** [comment]
Nope the new commit still doesn't work.
```
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 1806, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/stable-diffusion-webui/modules/extras.py", line 353, in run_modelmerger
    theta_1 = sd_models.read_state_dict(secondary_model_info.filename, map_location=devices.get_optimal_device())
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 220, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
Exception: device cuda is invalid```

Anyways i have a request.. Custom vae and lora addition when?

**Comment by acheong08** [comment]
> Exception: device cuda is invalid


I found the issue: You are using a safetensors model. You need to select the safetensors option in checkpoint format

**Comment by acheong08** [comment]
Side note, you can't merge safetensors and ckpt together

**Comment by Rorutop** [comment]
Tbh I still couldn't merge 2 safetensors, that's unfortunate :/
I thought there was a new update or something

**Comment by acheong08** [comment]
Check again. I updated a few things
