### ISSUE TITLE
Latest bug

### ISSUE THREAD

**Issue by Enferlain** [acheong08/Diffusion-ColabUI#91]
Can you fix this? Or any manual workaround until it's fixed?

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7714

Traceback (most recent call last):
  File "launch.py", line 361, in <module>
    start()
  File "launch.py", line 356, in start
    webui.webui()
  File "/content/stable-diffusion-webui/webui.py", line 232, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 135, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
Killing tunnel 127.0.0.1:7860 <> https://6e3a60eb-b1f1-4f17.gradio.live/
^C

**Comment by acheong08** [comment]
Check if fixed https://github.com/acheong08/stable-diffusion-webui/commit/48e76521d0b5112b95861686536c611c73262075

**Comment by GoAwayNow** [comment]
That does fix it. 0.90.1 works, too.

**Comment by GoAwayNow** [comment]
Woah, actually, not fixed. For some reason, requirements_versions.txt is being totally ignored for me! When I tested, just about everything in the file is installed as the wrong version.

**Comment by qa13683954882** [comment]
Replace the original REQS_FILE="requirements.txt" 👈👉 REQS_FILE="requirements_versions.txt" 

Fix this problem ：Cannot add middleware after an application has started

The fundamental reason is the 0.91 version of Fastapi. 

Fastapi 0.90.1 0.90 0.89 is ok.

**Comment by GoAwayNow** [comment]
> Replace the original REQS_FILE="requirements.txt" 👈👉 REQS_FILE="requirements_versions.txt"

Don't do that. Requirements_versions.txt doesn't have all of the requirements in it.

**Comment by acheong08** [comment]
Solution is to put fastapi version in both. I'll do that

**Comment by acheong08** [comment]
https://github.com/acheong08/stable-diffusion-webui/commit/44de47784af1fb12cb1cb17b8ea0a983d4ece977
