### ISSUE TITLE
error: Your local changes to the following files would be overwritten by checkout: 	train.py

### ISSUE THREAD

**Issue by re231** [acheong08/Diffusion-ColabUI#92]
i get this error when trying to launch on google drive

Traceback (most recent call last):
  File "launch.py", line 360, in <module>
    prepare_environment()
  File "launch.py", line 302, in prepare_environment
    git_clone(k_diffusion_repo, repo_dir('k-diffusion'), "K-diffusion", k_diffusion_commit_hash)
  File "launch.py", line 162, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', None, "Couldn't checkout {name}'s hash: {commithash}")
  File "launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout {name}'s hash: {commithash}.
Command: "git" -C "repositories/k-diffusion" checkout 5b3af030dd83e0297272d861c19477735d0317ec
Error code: 1
stdout: <empty>
stderr: error: Your local changes to the following files would be overwritten by checkout:
	train.py
Please commit your changes or stash them before you switch branches.
Aborting

**Comment by re231** [comment]
update:
i manage to launch the gradio after deleting the train.py, will update again.
